//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.5
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace ClientDocumentation.Web.Models.ModelsBuilder
{
	/// <summary>Client Master Data Item</summary>
	[PublishedModel("clientMasterDataItem")]
	public partial class ClientMasterDataItem : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const string ModelTypeAlias = "clientMasterDataItem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ClientMasterDataItem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ClientMasterDataItem(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("address")]
		public virtual global::System.Collections.Generic.IEnumerable<global::ClientDocumentation.Web.Models.ModelsBuilder.ClientAddressItem> Address => this.Value<global::System.Collections.Generic.IEnumerable<global::ClientDocumentation.Web.Models.ModelsBuilder.ClientAddressItem>>("address");

		///<summary>
		/// Client since
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("clientSince")]
		public virtual global::System.DateTime ClientSince => this.Value<global::System.DateTime>("clientSince");

		///<summary>
		/// Client Stakeholders
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("clientStakeholders")]
		public virtual global::System.Collections.Generic.IEnumerable<global::ClientDocumentation.Web.Models.ModelsBuilder.Person> ClientStakeholders => this.Value<global::System.Collections.Generic.IEnumerable<global::ClientDocumentation.Web.Models.ModelsBuilder.Person>>("clientStakeholders");

		///<summary>
		/// AKQA Team
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("teamMembers")]
		public virtual global::System.Collections.Generic.IEnumerable<global::ClientDocumentation.Web.Models.ModelsBuilder.UserPickerNC> TeamMembers => this.Value<global::System.Collections.Generic.IEnumerable<global::ClientDocumentation.Web.Models.ModelsBuilder.UserPickerNC>>("teamMembers");
	}
}
